//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Глазки_Saves
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Windows.Media;

    public partial class ProductSale
    {
        public int ID { get; set; }
        public int AgentID { get; set; }
        public int ProductID { get; set; }
        public System.DateTime SaleDate { get; set; }
        public int ProductCount { get; set; }
    
        public virtual Agent Agent { get; set; }
        public virtual Product Product { get; set; }

        private static EyesEntities _context;
        public static EyesEntities GetContext()
        {
            if (_context == null)
            {
                _context = new EyesEntities();
            }
            return _context;
        }
        public string ProductName
        {
            get
            {
                return Product.Title;
            }
            set
            {
                Product.Title = value;
            }
        }
        public string SaleDateText
        {
            get
            {
                return SaleDate.ToShortDateString();
            }
        }
        public int SaleCount
        {
            get
            {
                return ProductCount;
            }
        }

        public int SumProd
        {
            get
            {
                int sum = 0;
                sum = GetContext().ProductSale
                .Where(s => s.AgentID == this.AgentID)
                .Sum(s => s.ProductCount);
                return sum;
            }
        }
        

    }

}
